---
- name: Create teleport service (SysVinit).
  template:
    src: "teleport.sysvinit.j2"
    dest: "/etc/init.d/teleport"
    owner: "root"
    group: "root"
    mode: 0744

- name: restart teleport
  shell: /etc/init.d/teleport restart
  become: yes
  when: teleport_installed.changed
