---
- name: Create teleport service (systemd).
  template:
    src: "teleport.service.j2"
    dest: "{{ systemd_service_dir }}/teleport.service"
    owner: "root"
    group: "root"
    mode: 0644
  register: service_installed

- name: systemctl daemon-reload
  shell: systemctl daemon-reload
  become: yes
  when: service_installed.changed

- name: restart teleport
  shell: systemctl restart teleport.service
  become: yes
  when: teleport_installed.changed
